
-- NO ES CORRECTO YA QUE ESTA LLAMANDO UNA VARIABLE DE UN DECLARE HIJO 
--POR TANTO NO PUEDE TOMAR EL DATO AL INICIO NI AL FINAL
BEGIN
DBMS_OUTPUT.PUT_LINE(X);
DECLARE
X NUMBER:=20;
BEGIN
DBMS_OUTPUT.PUT_LINE(X);
END;
DBMS_OUTPUT.PUT_LINE(X);
END;
