//CALCULANDO EL IMPUESTO DE UN PRODUCTO

SET SERVEROUTPUT ON

DECLARE
IMP CONSTANT NUMBER:=21;
PRECIO NUMBER(5,2);
RESULTADO PRECIO%TYPE;

BEGIN
PRECIO:=40;
RESULTADO:= PRECIO * IMP /100;

DBMS_OUTPUT.PUT_LINE('El Producto vale '|| PRECIO ||' Dolares y aplicando el impuesto es de '|| RESULTADO || ' Dolares');

END;