SET SERVEROUTPUT ON
--INICIALES EN MAYUSCULAS EJEMPLO A.P.D
DECLARE
NOMBRE VARCHAR(100):='daniel';
APELLIDO1 VARCHAR(100):='paredes';
APELLIDO2 VARCHAR(100):='alvarez';

BEGIN

DBMS_OUTPUT.PUT_LINE(substr(UPPER(NOMBRE),0,1)||'.' || substr(UPPER(APELLIDO1),0,1) || '.' || substr(UPPER(APELLIDO2),0,1)  );


-- DIA QUE NACI
DECLARE

FECHA DATE;

BEGIN

fecha:= TO_DATE('04/05/1998','DD/MM/YYYY');

DBMS_OUTPUT.PUT_LINE('NACI UN DIA COMO HOY EN' || fecha || ' Siendo el dia ' || TO_CHAR(fecha,'DAY'));


END;


END;