Set serveroutput on
DECLARE
NOMBRE_EMPLEADO EMPLOYEES.FIRST_NAME%TYPE;
BEGIN
 SELECT FIRST_NAME INTO NOMBRE_EMPLEADO FROM EMPLOYEES WHERE EMPLOYEE_ID=1000;
 DBMS_OUTPUT.PUT_LINE(NOMBRE_EMPLEADO);
EXCEPTION
 WHEN NO_DATA_FOUND THEN
 DBMS_OUTPUT.PUT_LINE('No existe el empleado.');
END;
/
